on:
  schedule:
  - cron: "0 13 * * *"
  
  workflow_dispatch:
  
jobs:
 run-uptime:
    runs-on: ubuntu-latest
    steps:
    - name: Uptime Action
      uses: srt32/uptime@v0.2.1
      with:
        # which url to hit
        url-to-hit:  "https://www.cjvillarreal.com/amazon-pie-scrapper/pie_price.json"
        # which http response statuses are expected
        expected-statuses: "200"
