# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update Pie Price

on: 
  schedule: 
      - cron: '0 0 * * *'
workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js latest
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - run: npm ci
    - run: npm run start
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Updating pie_price.json"
        commit_user_name: cjvillar

